
def euler2(upper_bound=1000000):
    """http://projecteuler.net/problem=2

    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.

    Find the sum of all the even-valued terms in the Fibonacci sequence which
    do not exceed one million.
    """
    f1, f2 = 2, 1
    even_sum = 0
    while f1 < upper_bound:
        if f1 % 2 == 0:
            even_sum = even_sum + f1
        f1, f2 = f1 + f2, f1
    return even_sum

